### PR TITLE
An introductory Kotlin talk by Drew Stephens

### PR DESCRIPTION
**Pull request by dinomite**

### CODE REVIEW

**Review by sahiltalwar88 — COMMENTED** [review]
@dinomite - we generally tend to either do 10ish minute lightning talks, workshops (2+ hours), or 1 hour talks. That's not to say that we couldn't accommodate you - we will certainly do our best - but is there any chance you could extend this talk to an hour?

**Comment by dinomite** [comment]
Got it.  I haven't yet run through this talk, but I'll do some practice next week and, along with some example usages I bet I can make it a full-fledged talk.  I'll get back to you.

**Comment by jenpen** [comment]
@dinomite - gauging your availability, but could you speak on the 22nd instead of the 17th? The ATX space we use is booked on the 17th so trying to explore other options.

**Comment by dinomite** [comment]
@jenpen Yep, I can do May 22nd

**Pull request merged**
