### PR TITLE
Streaming talk and Fp workshop

### PR DESCRIPTION
**Pull request by rikace**
Adding Stream Processing talk and Functional workshop

### CODE REVIEW

**Comment by jenpen** [comment]
@rikace - thanks so much for your PR! Would November work for you?

**Comment by rikace** [comment]
November looks good, but I will be no available between the  12-19

**Review by PatLeong — APPROVED** [review]
I approve! @jenpen, @Wyntuition, and @duluca thoughts?

**Comment by duluca** [comment]
👍

**Pull request merged**
