### PR TITLE
Added ASP.NET Core 1.0 talk

### PR DESCRIPTION
**Pull request by ebt-techtalk**

### CODE REVIEW

**Comment by duluca** [comment]
@ebt-techtalk Thanks a lot for your submission. Would October 19th work for you?

**Comment by ebt-techtalk** [comment]
Yes, I'm free on that day, but will confirm around late August (visa pending). My talk will not fit into 1 hour with all it's content, would take 90 min.

**Comment by duluca** [comment]
Ok please keep me posted. Good luck.

**Comment by duluca** [comment]
@ebt-techtalk any update on your situation?

**Comment by ebt-techtalk** [comment]
Everything is okay, I will be ready to have a talk.

**Comment by duluca** [comment]
Fantastic. I'll put your event on Meetup.com then.

**Comment by duluca** [comment]
@ebt-techtalk Scheduled the meetup http://www.meetup.com/TechTalkDC/events/233563947/ Let me know if you need a change made. We can also schedule a video chat a week before to discuss details if you need it.

**Comment by ebt-techtalk** [comment]
Please change “(comming out Jume 27)” to “(released as 1.0.0 in June)”.
Thank you.

**Pull request merged**
