### PR TITLE
Added Vladimir Bychkov

### PR DESCRIPTION
**Pull request by bychkov**

### CODE REVIEW

**Comment by duluca** [comment]
@bychkov Thanks a lot for submitting this. I'm planning to schedule this talk for Wednesday 9/21. Does that work?

**Comment by bychkov** [comment]
Hi Doguhan,

I just found my reply in the drafts folder, so I'm not sure if you received
it. If the date still available 9/21 works for me.

Thanks,
Vladimir

**Comment by duluca** [comment]
@bychkov Sorry I didn't hear from you until yesterday. Meanwhile I had another request come in, so I had to re-book the September slot. I'm right now in the process of confirming the October slot. Would you be okay with 10/19 or 11/16 instead?

**Comment by duluca** [comment]
I just got confirmation for the October slot, will 11/16 work?

**Comment by bychkov** [comment]
11/16 is good. Thanks.

**Comment by duluca** [comment]
@bychkov Great. Create the event page: http://www.meetup.com/TechTalkDC/events/233565299/ Let me know if you'd like any changes to it and also if you want we can setup a video chat a week before the event to discuss any details.

**Comment by bychkov** [comment]
Thanks Doguhan! Looks good. I'll send you some updates closer to the
presentation date.We can also do video chat week prior to the event.

**Pull request merged**
