### PR TITLE
propose ACRUMEN talk

### PR DESCRIPTION
**Pull request by davearonson**
I propose to do a half-hour talk (can extend if needed) on the key aspects of software quality, organized into priority order in a handy acronym, with a little bit on how to achieve each aspect.  See PR changes for further details.

### CODE REVIEW

**Comment by jenpen** [comment]
Hey Dave! Thanks so much for your PR. Do you have a blog entry you could point us to that might give more information about the talk?

**Comment by davearonson** [comment]
Blog entry, no, sorry, but if you watch the five-minute video I mention in the PR, it gives you an overview of the aspects in question.  Imagine that fleshed out with one to five slides on each aspect explaining it in a bit more depth, and then one to five explaining some basic ways how to achieve it.  The latest count, since I've been working on "more slides, less text on each" (on the advice of the Toptal Speakers Network) is fifty -- yes, it's still about 30 minutes.  I might be able to send you a screencast of the latest rehearsal.

Also, I'll be doing it at the Joy of Programming meetup next Wednesday.

**Comment by PatLeong** [comment]
Hey Dave, I think this is a great talk! However, we were thinking about doing a double-header for this month's meetup.  Do you think that you can deliver this as a lightning talk?  Then we'll be able to cover two topics for the price of one!  Please let us know if that works, and I'll merge your PR.

**Comment by davearonson** [comment]
I could, but it would be an extremely brief overview, basically an intro to what the aspects _are_, with little to no explanation of the nuances of the definitions or advice on how to _achieve_ them.  After adding very brief nuances and a tiny bit of advice, it was hard to keep it under half an hour last night.  Also I'm trying to practice the longer version because I've submitted it to some conferences.  :-)  Perhaps I could do a lightning talk at that meeting, and the half-hour version later?

**Comment by PatLeong** [comment]
I think thats a great idea. objections @jenpen and @justdroo?

**Comment by PatLeong** [comment]
Okay, we'll merge this as a lightning talk for the march meetup, and we'll schedule the 30 minute talk for later this year.  Your talk will be scheduled for March 28th 2018 before @SeanKilleen's talk.  Thanks for submitting!

**Pull request merged**
